import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserIdProvider } from "@/provider/UserIdProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hintro Dashboard",
  description: "Generated by hintro dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <UserIdProvider>{children}</UserIdProvider>
      </body>
    </html>
  );
}
